"""empty message

Revision ID: 00826de0a1f0
Revises: 644095397812
Create Date: 2017-03-22 20:53:57.149323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00826de0a1f0'
down_revision = '644095397812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
