"""empty message

Revision ID: 644095397812
Revises: 86d075e8a791
Create Date: 2017-03-22 20:48:44.510235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644095397812'
down_revision = '86d075e8a791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
